version: "3.9"

services:
  cassandra-seed:
    image: cassandra:latest
    container_name: Seed
    volumes:
      - ../../cassandra_data_seed:/var/lib/cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=driver-cluster"
      - "CASSANDRA_DC=driver-datacenter"
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    expose:
      - 9042
    ports:
      - "9042:9042"

  cassandra-first-node:
    image: cassandra:latest
    container_name: First-node
    volumes:
      - ../../cassandra_data:/var/lib/cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=driver-cluster"
      - "CASSANDRA_DC=driver-datacenter"
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    depends_on:
      - cassandra-seed

  cassandra-second-node:
    image: cassandra:latest
    container_name: Second-node
    volumes:
      - ../../cassandra_second_data:/var/lib/cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=driver-cluster"
      - "CASSANDRA_DC=driver-datacenter"
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    depends_on:
      - cassandra-seed

  driverservice:
    container_name: driver-service
    restart: on-failure
    build:
      dockerfile: ./deployments/dockerfile
      context: ../
    env_file:
      - ../internal/configs/connection.env
    ports:
      - "80:80"
    depends_on:
      - cassandra-seed
      - cassandra-second-node
      - cassandra-first-node
    links:
      - cassandra-seed
      - cassandra-second-node
      - cassandra-first-node