/*
 * Driver Service Inno Taxi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto

type DeleteDriverRequest struct {
	Id int32 `json:"id,omitempty"`
}
