/*
 * Driver Service Inno Taxi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto

type GetDriverRating struct {
	Rating int32 `json:"Rating,omitempty"`
}
