/*
 * Driver Service Inno Taxi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto

type GetDriverResponse struct {
	PhoneNumber string `json:"phoneNumber"`
	Name        string `json:"name"`
	TaxiType    string `json:"taxiType"`
}
