/*
 * Driver Service Inno Taxi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto

type Driver struct {
	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	PhoneNumber string `json:"phoneNumber,omitempty"`

	TaxiType string `json:"taxiType,omitempty"`
}
