/*
 * Driver Service Inno Taxi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto

type ChangeDriverRequest struct {
	NewName string `json:"newName,omitempty"`

	NewEmail string `json:"newEmail,omitempty"`

	NewPhoneNumber string `json:"newPhoneNumber,omitempty"`

	NewTaxiType string `json:"newTaxiType,omitempty"`
}
