// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DrownSelf/DriverService/models"
)

// GetDriverOKCode is the HTTP code returned for type GetDriverOK
const GetDriverOKCode int = 200

/*
GetDriverOK OK

swagger:response getDriverOK
*/
type GetDriverOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetDriverResponse `json:"body,omitempty"`
}

// NewGetDriverOK creates GetDriverOK with default headers values
func NewGetDriverOK() *GetDriverOK {

	return &GetDriverOK{}
}

// WithPayload adds the payload to the get driver o k response
func (o *GetDriverOK) WithPayload(payload *models.GetDriverResponse) *GetDriverOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver o k response
func (o *GetDriverOK) SetPayload(payload *models.GetDriverResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDriverBadRequestCode is the HTTP code returned for type GetDriverBadRequest
const GetDriverBadRequestCode int = 400

/*
GetDriverBadRequest Bad request. Cause can be invalid token.

swagger:response getDriverBadRequest
*/
type GetDriverBadRequest struct {
}

// NewGetDriverBadRequest creates GetDriverBadRequest with default headers values
func NewGetDriverBadRequest() *GetDriverBadRequest {

	return &GetDriverBadRequest{}
}

// WriteResponse to the client
func (o *GetDriverBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
