// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDriverLogoutHandlerFunc turns a function with the right signature into a get driver logout handler
type GetDriverLogoutHandlerFunc func(GetDriverLogoutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDriverLogoutHandlerFunc) Handle(params GetDriverLogoutParams) middleware.Responder {
	return fn(params)
}

// GetDriverLogoutHandler interface for that can handle valid get driver logout params
type GetDriverLogoutHandler interface {
	Handle(GetDriverLogoutParams) middleware.Responder
}

// NewGetDriverLogout creates a new http.Handler for the get driver logout operation
func NewGetDriverLogout(ctx *middleware.Context, handler GetDriverLogoutHandler) *GetDriverLogout {
	return &GetDriverLogout{Context: ctx, Handler: handler}
}

/*
	GetDriverLogout swagger:route GET /driver/logout Actions with token getDriverLogout

log out from session
*/
type GetDriverLogout struct {
	Context *middleware.Context
	Handler GetDriverLogoutHandler
}

func (o *GetDriverLogout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDriverLogoutParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
