// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDriverLogoutOKCode is the HTTP code returned for type GetDriverLogoutOK
const GetDriverLogoutOKCode int = 200

/*
GetDriverLogoutOK OK

swagger:response getDriverLogoutOK
*/
type GetDriverLogoutOK struct {
}

// NewGetDriverLogoutOK creates GetDriverLogoutOK with default headers values
func NewGetDriverLogoutOK() *GetDriverLogoutOK {

	return &GetDriverLogoutOK{}
}

// WriteResponse to the client
func (o *GetDriverLogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetDriverLogoutBadRequestCode is the HTTP code returned for type GetDriverLogoutBadRequest
const GetDriverLogoutBadRequestCode int = 400

/*
GetDriverLogoutBadRequest Bad request. Cause can be that you logged out before or haven't sign in.

swagger:response getDriverLogoutBadRequest
*/
type GetDriverLogoutBadRequest struct {
}

// NewGetDriverLogoutBadRequest creates GetDriverLogoutBadRequest with default headers values
func NewGetDriverLogoutBadRequest() *GetDriverLogoutBadRequest {

	return &GetDriverLogoutBadRequest{}
}

// WriteResponse to the client
func (o *GetDriverLogoutBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
