// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDriverHandlerFunc turns a function with the right signature into a get driver handler
type GetDriverHandlerFunc func(GetDriverParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDriverHandlerFunc) Handle(params GetDriverParams) middleware.Responder {
	return fn(params)
}

// GetDriverHandler interface for that can handle valid get driver params
type GetDriverHandler interface {
	Handle(GetDriverParams) middleware.Responder
}

// NewGetDriver creates a new http.Handler for the get driver operation
func NewGetDriver(ctx *middleware.Context, handler GetDriverHandler) *GetDriver {
	return &GetDriver{Context: ctx, Handler: handler}
}

/*
	GetDriver swagger:route GET /driver Actions with token getDriver

Respond info about driver. To get info you need token(to be authorized)
*/
type GetDriver struct {
	Context *middleware.Context
	Handler GetDriverHandler
}

func (o *GetDriver) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDriverParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
