// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/DrownSelf/DriverService/models"
)

// NewPostOrderRateDriverParams creates a new PostOrderRateDriverParams object
//
// There are no default values defined in the spec.
func NewPostOrderRateDriverParams() PostOrderRateDriverParams {

	return PostOrderRateDriverParams{}
}

// PostOrderRateDriverParams contains all the bound params for the post order rate driver operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostOrderRateDriver
type PostOrderRateDriverParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Adding rate to driver
	  In: body
	*/
	RequestToAddRatingToDriver *models.OrderRateRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostOrderRateDriverParams() beforehand.
func (o *PostOrderRateDriverParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.OrderRateRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("requestToAddRatingToDriver", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RequestToAddRatingToDriver = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
