// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDriverTakeOrderHandlerFunc turns a function with the right signature into a post driver take order handler
type PostDriverTakeOrderHandlerFunc func(PostDriverTakeOrderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDriverTakeOrderHandlerFunc) Handle(params PostDriverTakeOrderParams) middleware.Responder {
	return fn(params)
}

// PostDriverTakeOrderHandler interface for that can handle valid post driver take order params
type PostDriverTakeOrderHandler interface {
	Handle(PostDriverTakeOrderParams) middleware.Responder
}

// NewPostDriverTakeOrder creates a new http.Handler for the post driver take order operation
func NewPostDriverTakeOrder(ctx *middleware.Context, handler PostDriverTakeOrderHandler) *PostDriverTakeOrder {
	return &PostDriverTakeOrder{Context: ctx, Handler: handler}
}

/*
	PostDriverTakeOrder swagger:route POST /driver/takeOrder Actions with token Actions with order postDriverTakeOrder

Request to take order from user which make order
*/
type PostDriverTakeOrder struct {
	Context *middleware.Context
	Handler PostDriverTakeOrderHandler
}

func (o *PostDriverTakeOrder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDriverTakeOrderParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
