// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOrderRateDriverOKCode is the HTTP code returned for type PostOrderRateDriverOK
const PostOrderRateDriverOKCode int = 200

/*
PostOrderRateDriverOK Successfully added

swagger:response postOrderRateDriverOK
*/
type PostOrderRateDriverOK struct {
}

// NewPostOrderRateDriverOK creates PostOrderRateDriverOK with default headers values
func NewPostOrderRateDriverOK() *PostOrderRateDriverOK {

	return &PostOrderRateDriverOK{}
}

// WriteResponse to the client
func (o *PostOrderRateDriverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostOrderRateDriverBadRequestCode is the HTTP code returned for type PostOrderRateDriverBadRequest
const PostOrderRateDriverBadRequestCode int = 400

/*
PostOrderRateDriverBadRequest Bad request

swagger:response postOrderRateDriverBadRequest
*/
type PostOrderRateDriverBadRequest struct {
}

// NewPostOrderRateDriverBadRequest creates PostOrderRateDriverBadRequest with default headers values
func NewPostOrderRateDriverBadRequest() *PostOrderRateDriverBadRequest {

	return &PostOrderRateDriverBadRequest{}
}

// WriteResponse to the client
func (o *PostOrderRateDriverBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostOrderRateDriverInternalServerErrorCode is the HTTP code returned for type PostOrderRateDriverInternalServerError
const PostOrderRateDriverInternalServerErrorCode int = 500

/*
PostOrderRateDriverInternalServerError Internal server error

swagger:response postOrderRateDriverInternalServerError
*/
type PostOrderRateDriverInternalServerError struct {
}

// NewPostOrderRateDriverInternalServerError creates PostOrderRateDriverInternalServerError with default headers values
func NewPostOrderRateDriverInternalServerError() *PostOrderRateDriverInternalServerError {

	return &PostOrderRateDriverInternalServerError{}
}

// WriteResponse to the client
func (o *PostOrderRateDriverInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
