// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDriverRateUserOKCode is the HTTP code returned for type PostDriverRateUserOK
const PostDriverRateUserOKCode int = 200

/*
PostDriverRateUserOK Successfully added

swagger:response postDriverRateUserOK
*/
type PostDriverRateUserOK struct {
}

// NewPostDriverRateUserOK creates PostDriverRateUserOK with default headers values
func NewPostDriverRateUserOK() *PostDriverRateUserOK {

	return &PostDriverRateUserOK{}
}

// WriteResponse to the client
func (o *PostDriverRateUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostDriverRateUserBadRequestCode is the HTTP code returned for type PostDriverRateUserBadRequest
const PostDriverRateUserBadRequestCode int = 400

/*
PostDriverRateUserBadRequest Bad request

swagger:response postDriverRateUserBadRequest
*/
type PostDriverRateUserBadRequest struct {
}

// NewPostDriverRateUserBadRequest creates PostDriverRateUserBadRequest with default headers values
func NewPostDriverRateUserBadRequest() *PostDriverRateUserBadRequest {

	return &PostDriverRateUserBadRequest{}
}

// WriteResponse to the client
func (o *PostDriverRateUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostDriverRateUserInternalServerErrorCode is the HTTP code returned for type PostDriverRateUserInternalServerError
const PostDriverRateUserInternalServerErrorCode int = 500

/*
PostDriverRateUserInternalServerError Internal server error

swagger:response postDriverRateUserInternalServerError
*/
type PostDriverRateUserInternalServerError struct {
}

// NewPostDriverRateUserInternalServerError creates PostDriverRateUserInternalServerError with default headers values
func NewPostDriverRateUserInternalServerError() *PostDriverRateUserInternalServerError {

	return &PostDriverRateUserInternalServerError{}
}

// WriteResponse to the client
func (o *PostDriverRateUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
