// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/DrownSelf/DriverService/models"
)

// NewPostDriverEndRideParams creates a new PostDriverEndRideParams object
//
// There are no default values defined in the spec.
func NewPostDriverEndRideParams() PostDriverEndRideParams {

	return PostDriverEndRideParams{}
}

// PostDriverEndRideParams contains all the bound params for the post driver end ride operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostDriverEndRide
type PostDriverEndRideParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Changing status of ride and make driver free
	  In: body
	*/
	ChangeStatusOfRequest *models.EndRideRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostDriverEndRideParams() beforehand.
func (o *PostDriverEndRideParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.EndRideRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("changeStatusOfRequest", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ChangeStatusOfRequest = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
