// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDriverRateUserHandlerFunc turns a function with the right signature into a post driver rate user handler
type PostDriverRateUserHandlerFunc func(PostDriverRateUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDriverRateUserHandlerFunc) Handle(params PostDriverRateUserParams) middleware.Responder {
	return fn(params)
}

// PostDriverRateUserHandler interface for that can handle valid post driver rate user params
type PostDriverRateUserHandler interface {
	Handle(PostDriverRateUserParams) middleware.Responder
}

// NewPostDriverRateUser creates a new http.Handler for the post driver rate user operation
func NewPostDriverRateUser(ctx *middleware.Context, handler PostDriverRateUserHandler) *PostDriverRateUser {
	return &PostDriverRateUser{Context: ctx, Handler: handler}
}

/*
	PostDriverRateUser swagger:route POST /driver/rateUser Actions with token Actions with order postDriverRateUser

Request to rate user after ride
*/
type PostDriverRateUser struct {
	Context *middleware.Context
	Handler PostDriverRateUserHandler
}

func (o *PostDriverRateUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDriverRateUserParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
