// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDriverEndRideOKCode is the HTTP code returned for type PostDriverEndRideOK
const PostDriverEndRideOKCode int = 200

/*
PostDriverEndRideOK OK

swagger:response postDriverEndRideOK
*/
type PostDriverEndRideOK struct {
}

// NewPostDriverEndRideOK creates PostDriverEndRideOK with default headers values
func NewPostDriverEndRideOK() *PostDriverEndRideOK {

	return &PostDriverEndRideOK{}
}

// WriteResponse to the client
func (o *PostDriverEndRideOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostDriverEndRideInternalServerErrorCode is the HTTP code returned for type PostDriverEndRideInternalServerError
const PostDriverEndRideInternalServerErrorCode int = 500

/*
PostDriverEndRideInternalServerError Internal error

swagger:response postDriverEndRideInternalServerError
*/
type PostDriverEndRideInternalServerError struct {
}

// NewPostDriverEndRideInternalServerError creates PostDriverEndRideInternalServerError with default headers values
func NewPostDriverEndRideInternalServerError() *PostDriverEndRideInternalServerError {

	return &PostDriverEndRideInternalServerError{}
}

// WriteResponse to the client
func (o *PostDriverEndRideInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
