// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DrownSelf/DriverService/models"
)

// PostDriverTakeOrderOKCode is the HTTP code returned for type PostDriverTakeOrderOK
const PostDriverTakeOrderOKCode int = 200

/*
PostDriverTakeOrderOK Successfully found

swagger:response postDriverTakeOrderOK
*/
type PostDriverTakeOrderOK struct {

	/*
	  In: Body
	*/
	Payload *models.DriverRideResponse `json:"body,omitempty"`
}

// NewPostDriverTakeOrderOK creates PostDriverTakeOrderOK with default headers values
func NewPostDriverTakeOrderOK() *PostDriverTakeOrderOK {

	return &PostDriverTakeOrderOK{}
}

// WithPayload adds the payload to the post driver take order o k response
func (o *PostDriverTakeOrderOK) WithPayload(payload *models.DriverRideResponse) *PostDriverTakeOrderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver take order o k response
func (o *PostDriverTakeOrderOK) SetPayload(payload *models.DriverRideResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverTakeOrderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverTakeOrderBadRequestCode is the HTTP code returned for type PostDriverTakeOrderBadRequest
const PostDriverTakeOrderBadRequestCode int = 400

/*
PostDriverTakeOrderBadRequest Bad Request

swagger:response postDriverTakeOrderBadRequest
*/
type PostDriverTakeOrderBadRequest struct {
}

// NewPostDriverTakeOrderBadRequest creates PostDriverTakeOrderBadRequest with default headers values
func NewPostDriverTakeOrderBadRequest() *PostDriverTakeOrderBadRequest {

	return &PostDriverTakeOrderBadRequest{}
}

// WriteResponse to the client
func (o *PostDriverTakeOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostDriverTakeOrderInternalServerErrorCode is the HTTP code returned for type PostDriverTakeOrderInternalServerError
const PostDriverTakeOrderInternalServerErrorCode int = 500

/*
PostDriverTakeOrderInternalServerError Internal error

swagger:response postDriverTakeOrderInternalServerError
*/
type PostDriverTakeOrderInternalServerError struct {
}

// NewPostDriverTakeOrderInternalServerError creates PostDriverTakeOrderInternalServerError with default headers values
func NewPostDriverTakeOrderInternalServerError() *PostDriverTakeOrderInternalServerError {

	return &PostDriverTakeOrderInternalServerError{}
}

// WriteResponse to the client
func (o *PostDriverTakeOrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
