// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/DrownSelf/DriverService/models"
)

// NewPostDriverTakeOrderParams creates a new PostDriverTakeOrderParams object
//
// There are no default values defined in the spec.
func NewPostDriverTakeOrderParams() PostDriverTakeOrderParams {

	return PostDriverTakeOrderParams{}
}

// PostDriverTakeOrderParams contains all the bound params for the post driver take order operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostDriverTakeOrder
type PostDriverTakeOrderParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Adding driver in waiting queue when find user order would create.
	  In: body
	*/
	RequestToAssignInWatingQueue *models.Driver
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostDriverTakeOrderParams() beforehand.
func (o *PostDriverTakeOrderParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Driver
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("requestToAssignInWatingQueue", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RequestToAssignInWatingQueue = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
