// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDriverEndRideHandlerFunc turns a function with the right signature into a post driver end ride handler
type PostDriverEndRideHandlerFunc func(PostDriverEndRideParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDriverEndRideHandlerFunc) Handle(params PostDriverEndRideParams) middleware.Responder {
	return fn(params)
}

// PostDriverEndRideHandler interface for that can handle valid post driver end ride params
type PostDriverEndRideHandler interface {
	Handle(PostDriverEndRideParams) middleware.Responder
}

// NewPostDriverEndRide creates a new http.Handler for the post driver end ride operation
func NewPostDriverEndRide(ctx *middleware.Context, handler PostDriverEndRideHandler) *PostDriverEndRide {
	return &PostDriverEndRide{Context: ctx, Handler: handler}
}

/*
	PostDriverEndRide swagger:route POST /driver/endRide Actions with token Actions with order postDriverEndRide

Request to end ride with user
*/
type PostDriverEndRide struct {
	Context *middleware.Context
	Handler PostDriverEndRideHandler
}

func (o *PostDriverEndRide) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDriverEndRideParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
