// Code generated by go-swagger; DO NOT EDIT.

package actions_with_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostOrderRateDriverHandlerFunc turns a function with the right signature into a post order rate driver handler
type PostOrderRateDriverHandlerFunc func(PostOrderRateDriverParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOrderRateDriverHandlerFunc) Handle(params PostOrderRateDriverParams) middleware.Responder {
	return fn(params)
}

// PostOrderRateDriverHandler interface for that can handle valid post order rate driver params
type PostOrderRateDriverHandler interface {
	Handle(PostOrderRateDriverParams) middleware.Responder
}

// NewPostOrderRateDriver creates a new http.Handler for the post order rate driver operation
func NewPostOrderRateDriver(ctx *middleware.Context, handler PostOrderRateDriverHandler) *PostOrderRateDriver {
	return &PostOrderRateDriver{Context: ctx, Handler: handler}
}

/*
	PostOrderRateDriver swagger:route POST /order/rateDriver Actions with token Actions with order postOrderRateDriver

Rate from user
*/
type PostOrderRateDriver struct {
	Context *middleware.Context
	Handler PostOrderRateDriverHandler
}

func (o *PostOrderRateDriver) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostOrderRateDriverParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
