// Code generated by go-swagger; DO NOT EDIT.

package logging_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDriverLoginHandlerFunc turns a function with the right signature into a post driver login handler
type PostDriverLoginHandlerFunc func(PostDriverLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDriverLoginHandlerFunc) Handle(params PostDriverLoginParams) middleware.Responder {
	return fn(params)
}

// PostDriverLoginHandler interface for that can handle valid post driver login params
type PostDriverLoginHandler interface {
	Handle(PostDriverLoginParams) middleware.Responder
}

// NewPostDriverLogin creates a new http.Handler for the post driver login operation
func NewPostDriverLogin(ctx *middleware.Context, handler PostDriverLoginHandler) *PostDriverLogin {
	return &PostDriverLogin{Context: ctx, Handler: handler}
}

/*
	PostDriverLogin swagger:route POST /driver/login Logging actions postDriverLogin

Log in driver in system.
*/
type PostDriverLogin struct {
	Context *middleware.Context
	Handler PostDriverLoginHandler
}

func (o *PostDriverLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDriverLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
