// Code generated by go-swagger; DO NOT EDIT.

package logging_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDriverRegisterHandlerFunc turns a function with the right signature into a post driver register handler
type PostDriverRegisterHandlerFunc func(PostDriverRegisterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDriverRegisterHandlerFunc) Handle(params PostDriverRegisterParams) middleware.Responder {
	return fn(params)
}

// PostDriverRegisterHandler interface for that can handle valid post driver register params
type PostDriverRegisterHandler interface {
	Handle(PostDriverRegisterParams) middleware.Responder
}

// NewPostDriverRegister creates a new http.Handler for the post driver register operation
func NewPostDriverRegister(ctx *middleware.Context, handler PostDriverRegisterHandler) *PostDriverRegister {
	return &PostDriverRegister{Context: ctx, Handler: handler}
}

/*
	PostDriverRegister swagger:route POST /driver/register Logging actions postDriverRegister

Register new driver in system.
*/
type PostDriverRegister struct {
	Context *middleware.Context
	Handler PostDriverRegisterHandler
}

func (o *PostDriverRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDriverRegisterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
