// Code generated by go-swagger; DO NOT EDIT.

package logging_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/DrownSelf/DriverService/models"
)

// NewPostDriverRegisterParams creates a new PostDriverRegisterParams object
//
// There are no default values defined in the spec.
func NewPostDriverRegisterParams() PostDriverRegisterParams {

	return PostDriverRegisterParams{}
}

// PostDriverRegisterParams contains all the bound params for the post driver register operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostDriverRegister
type PostDriverRegisterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*object which you need send to register
	  In: body
	*/
	RegisterRequest *models.Driver
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostDriverRegisterParams() beforehand.
func (o *PostDriverRegisterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Driver
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("registerRequest", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RegisterRequest = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
