// Code generated by go-swagger; DO NOT EDIT.

package logging_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DrownSelf/DriverService/models"
)

// PostDriverLoginOKCode is the HTTP code returned for type PostDriverLoginOK
const PostDriverLoginOKCode int = 200

/*
PostDriverLoginOK OK

swagger:response postDriverLoginOK
*/
type PostDriverLoginOK struct {

	/*
	  In: Body
	*/
	Payload models.Token `json:"body,omitempty"`
}

// NewPostDriverLoginOK creates PostDriverLoginOK with default headers values
func NewPostDriverLoginOK() *PostDriverLoginOK {

	return &PostDriverLoginOK{}
}

// WithPayload adds the payload to the post driver login o k response
func (o *PostDriverLoginOK) WithPayload(payload models.Token) *PostDriverLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver login o k response
func (o *PostDriverLoginOK) SetPayload(payload models.Token) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostDriverLoginBadRequestCode is the HTTP code returned for type PostDriverLoginBadRequest
const PostDriverLoginBadRequestCode int = 400

/*
PostDriverLoginBadRequest Bad request. Cause can be wrong password or absense of user.

swagger:response postDriverLoginBadRequest
*/
type PostDriverLoginBadRequest struct {
}

// NewPostDriverLoginBadRequest creates PostDriverLoginBadRequest with default headers values
func NewPostDriverLoginBadRequest() *PostDriverLoginBadRequest {

	return &PostDriverLoginBadRequest{}
}

// WriteResponse to the client
func (o *PostDriverLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostDriverLoginInternalServerErrorCode is the HTTP code returned for type PostDriverLoginInternalServerError
const PostDriverLoginInternalServerErrorCode int = 500

/*
PostDriverLoginInternalServerError Internal server error.

swagger:response postDriverLoginInternalServerError
*/
type PostDriverLoginInternalServerError struct {
}

// NewPostDriverLoginInternalServerError creates PostDriverLoginInternalServerError with default headers values
func NewPostDriverLoginInternalServerError() *PostDriverLoginInternalServerError {

	return &PostDriverLoginInternalServerError{}
}

// WriteResponse to the client
func (o *PostDriverLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
