// Code generated by go-swagger; DO NOT EDIT.

package logging_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DrownSelf/DriverService/models"
)

// PostDriverRegisterCreatedCode is the HTTP code returned for type PostDriverRegisterCreated
const PostDriverRegisterCreatedCode int = 201

/*
PostDriverRegisterCreated Driver created and return id

swagger:response postDriverRegisterCreated
*/
type PostDriverRegisterCreated struct {

	/*
	  In: Body
	*/
	Payload models.ID `json:"body,omitempty"`
}

// NewPostDriverRegisterCreated creates PostDriverRegisterCreated with default headers values
func NewPostDriverRegisterCreated() *PostDriverRegisterCreated {

	return &PostDriverRegisterCreated{}
}

// WithPayload adds the payload to the post driver register created response
func (o *PostDriverRegisterCreated) WithPayload(payload models.ID) *PostDriverRegisterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver register created response
func (o *PostDriverRegisterCreated) SetPayload(payload models.ID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverRegisterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostDriverRegisterBadRequestCode is the HTTP code returned for type PostDriverRegisterBadRequest
const PostDriverRegisterBadRequestCode int = 400

/*
PostDriverRegisterBadRequest Bad request. Cause can be invalid data.

swagger:response postDriverRegisterBadRequest
*/
type PostDriverRegisterBadRequest struct {
}

// NewPostDriverRegisterBadRequest creates PostDriverRegisterBadRequest with default headers values
func NewPostDriverRegisterBadRequest() *PostDriverRegisterBadRequest {

	return &PostDriverRegisterBadRequest{}
}

// WriteResponse to the client
func (o *PostDriverRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostDriverRegisterInternalServerErrorCode is the HTTP code returned for type PostDriverRegisterInternalServerError
const PostDriverRegisterInternalServerErrorCode int = 500

/*
PostDriverRegisterInternalServerError Internal server error.

swagger:response postDriverRegisterInternalServerError
*/
type PostDriverRegisterInternalServerError struct {
}

// NewPostDriverRegisterInternalServerError creates PostDriverRegisterInternalServerError with default headers values
func NewPostDriverRegisterInternalServerError() *PostDriverRegisterInternalServerError {

	return &PostDriverRegisterInternalServerError{}
}

// WriteResponse to the client
func (o *PostDriverRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
