// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Driver Service Inno Taxi
//
//	Schemes:
//	  http
//	Host: localhost:8081
//	BasePath: /
//	Version: 1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - applications/json
//	  - application/json
//
// swagger:meta
package restapi
