// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Driver Service Inno Taxi",
    "version": "1.0"
  },
  "host": "localhost:8081",
  "paths": {
    "/driver": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token"
        ],
        "summary": "Respond info about driver. To get info you need token(to be authorized)",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/GetDriverResponse"
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid token."
          }
        }
      }
    },
    "/driver/endRide": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Request to end ride with user",
        "parameters": [
          {
            "description": "Changing status of ride and make driver free",
            "name": "Change status of request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/EndRideRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/driver/login": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Logging actions"
        ],
        "summary": "Log in driver in system.",
        "parameters": [
          {
            "description": "object which you need send to login",
            "name": "log in request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/LogInDriverRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/token"
            }
          },
          "400": {
            "description": "Bad request. Cause can be wrong password or absense of user."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/driver/logout": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token"
        ],
        "summary": "log out from session",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request. Cause can be that you logged out before or haven't sign in."
          }
        }
      }
    },
    "/driver/rateUser": {
      "post": {
        "produces": [
          "applications/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Request to rate user after ride",
        "parameters": [
          {
            "description": "Add rating to user",
            "name": "Request to rate user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/RateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully added"
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/driver/register": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Logging actions"
        ],
        "summary": "Register new driver in system.",
        "parameters": [
          {
            "description": "object which you need send to register",
            "name": "Register Request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Driver"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Driver created and return id",
            "schema": {
              "$ref": "#/definitions/id"
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid data."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/driver/takeOrder": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Request to take order from user which make order",
        "parameters": [
          {
            "description": "Adding driver in waiting queue when find user order would create.",
            "name": "Request to assign in wating queue",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Driver"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully found",
            "schema": {
              "$ref": "#/definitions/DriverRideResponse"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/order/rateDriver": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Rate from user",
        "parameters": [
          {
            "description": "Adding rate to driver",
            "name": "Request to add rating to driver",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/OrderRateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully added"
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Driver": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "taxiType": {
          "type": "string"
        }
      }
    },
    "DriverRideResponse": {
      "type": "object",
      "properties": {
        "From": {
          "type": "string"
        },
        "OrderId": {
          "type": "string"
        },
        "To": {
          "type": "string"
        },
        "UserName": {
          "type": "string"
        },
        "UserPhoneNumber": {
          "type": "string"
        }
      }
    },
    "EndRideRequest": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        }
      }
    },
    "GetDriverResponse": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "taxiType": {
          "type": "string"
        }
      }
    },
    "LogInDriverRequest": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        }
      }
    },
    "OrderRateRequest": {
      "properties": {
        "phoneNumber": {
          "type": "string"
        },
        "rating": {
          "type": "integer"
        }
      }
    },
    "RateUserRequest": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "rating": {
          "type": "integer"
        }
      }
    },
    "id": {
      "type": "integer"
    },
    "token": {
      "type": "string"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Driver Service Inno Taxi",
    "version": "1.0"
  },
  "host": "localhost:8081",
  "paths": {
    "/driver": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token"
        ],
        "summary": "Respond info about driver. To get info you need token(to be authorized)",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/GetDriverResponse"
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid token."
          }
        }
      }
    },
    "/driver/endRide": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Request to end ride with user",
        "parameters": [
          {
            "description": "Changing status of ride and make driver free",
            "name": "Change status of request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/EndRideRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/driver/login": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Logging actions"
        ],
        "summary": "Log in driver in system.",
        "parameters": [
          {
            "description": "object which you need send to login",
            "name": "log in request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/LogInDriverRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/token"
            }
          },
          "400": {
            "description": "Bad request. Cause can be wrong password or absense of user."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/driver/logout": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token"
        ],
        "summary": "log out from session",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request. Cause can be that you logged out before or haven't sign in."
          }
        }
      }
    },
    "/driver/rateUser": {
      "post": {
        "produces": [
          "applications/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Request to rate user after ride",
        "parameters": [
          {
            "description": "Add rating to user",
            "name": "Request to rate user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/RateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully added"
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/driver/register": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Logging actions"
        ],
        "summary": "Register new driver in system.",
        "parameters": [
          {
            "description": "object which you need send to register",
            "name": "Register Request",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Driver"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Driver created and return id",
            "schema": {
              "$ref": "#/definitions/id"
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid data."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/driver/takeOrder": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Request to take order from user which make order",
        "parameters": [
          {
            "description": "Adding driver in waiting queue when find user order would create.",
            "name": "Request to assign in wating queue",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Driver"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully found",
            "schema": {
              "$ref": "#/definitions/DriverRideResponse"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/order/rateDriver": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Actions with token",
          "Actions with order"
        ],
        "summary": "Rate from user",
        "parameters": [
          {
            "description": "Adding rate to driver",
            "name": "Request to add rating to driver",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/OrderRateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully added"
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Driver": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "taxiType": {
          "type": "string"
        }
      }
    },
    "DriverRideResponse": {
      "type": "object",
      "properties": {
        "From": {
          "type": "string"
        },
        "OrderId": {
          "type": "string"
        },
        "To": {
          "type": "string"
        },
        "UserName": {
          "type": "string"
        },
        "UserPhoneNumber": {
          "type": "string"
        }
      }
    },
    "EndRideRequest": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        }
      }
    },
    "GetDriverResponse": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "taxiType": {
          "type": "string"
        }
      }
    },
    "LogInDriverRequest": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        }
      }
    },
    "OrderRateRequest": {
      "properties": {
        "phoneNumber": {
          "type": "string"
        },
        "rating": {
          "type": "integer"
        }
      }
    },
    "RateUserRequest": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "rating": {
          "type": "integer"
        }
      }
    },
    "id": {
      "type": "integer"
    },
    "token": {
      "type": "string"
    }
  }
}`))
}
