/*
 * Driver Service Inno Taxi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	"DriverService/internal/app/auth"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "DriverService/internal/app/handlers"
	"DriverService/internal/app/repositories"
	"DriverService/internal/app/services"
	"DriverService/internal/pkg/configs"
)

func main() {
	log.Printf("Server started")
	config, err := configs.LoadConnectionConfig()
	if err != nil {
		log.Fatalf("error during loading config: %v", err)
	}

	repository, err := repositories.NewDriverRepository(*config)
	if err != nil {
		log.Fatalf("error during connecting db: %v", err)
	}
	service := services.NewDriverService(repository, &auth.Hasher{})
	handler := sw.NewHanlder(service, *config)
	router := sw.NewRouter(handler)

	log.Fatal(http.ListenAndServe(":"+config.AppPort, router))
}
