// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "info": {
    "title": "Driver Service Inno Taxi",
    "version": "1.0"
  },
  "securityDefinitions": {
    "JWT": {
      "type": "apiKey",
      "in": "header",
      "name": "Authorization"
    }
  },
  "definitions": {
    "dto.Driver": {
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "taxiType": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "dto.LogInDriverRequest": {
      "properties": {
        "phoneNumber": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "dto.GetDriverResponse": {
      "properties": {
        "name": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "taxiType": {
          "type": "string"
        }
      },
      "type": "object"
    },
	"dto.ChangeDriverStatus": {
      "properties" :{
		"status": {
		  "type": "boolean"
          }
		},
      "type" : "object"
	},
    "id": {
      "type": "integer"
    },
    
    "token": {
      "type": "string"
    }
  },
  "paths": {
    "/api/v1/driver": {
      "get": {
        "summary": "Respond info about driver. To get info you need token(to be authorized)",
        "security": [
          {
            "JWT": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "$ref": "#/definitions/dto.GetDriverResponse"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid token."
          }
        },
        "tags": [
          "Actions with token"
        ]
      }
    },
    "/api/v1/driver/login": {
      "post": {
        "summary": "Log in driver in system.",
        "parameters": [
          {
            "name": "log in request",
            "in": "body",
            "description": "object which you need send to login",
            "schema": {
              "$ref": "#/definitions/dto.LogInDriverRequest"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "$ref": "#/definitions/token"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be wrong password or absense of user."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/driver/register": {
      "post": {
        "summary": "Register new driver in system.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Register Request",
            "in": "body",
            "description": "object which you need send to register",
            "schema": {
              "$ref": "#/definitions/dto.Driver"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Driver created and return id",
            "schema": {
              "items": {
                "$ref": "#/definitions/id"
              }
            }
          },
          "400": {
            "description": "Bad request. Cause can be invalid data."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    },
    "/api/v1/driver/status": {
      "put": {
        "summary": "Change status of driver",
        "security": [
          {
            "JWT": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "param to set driver status",
            "in": "body",
            "description": "object which you need send to change status",
            "schema": {
              "$ref": "#/definitions/dto.ChangeDriverStatus"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request. Cause can be invalid data."
          },
          "500": {
            "description": "Internal server error."
          }
        }
      }
    }
  },
  "host": "localhost:8080",
  "swagger": "2.0"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
