name: CI/CD

on:
  push:
  pull_request:

jobs:
  testAndLint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y && sudo apt install openssh-client git -y
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Creds
        run: echo ${GH_CREDS} >> ~/.netrc

      - name: Set envar
        run: export GOPRIVATE=github.com/DrownSelf

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Install golangci
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

      - name: Run linter
        run: golangci-lint run
        
      - name: Run tests
        run: go test -race -vet=off ./...