name: CI/CD

on:
  push:
  pull_request:

jobs:
  testAndLint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && apt install -y openssh-client git
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Enable ssh agent
        run: eval `ssh-agent -s`

      - name: Add private key for repo
        env:
          KEY: ${{ secrets.KEYFORORDER }}
        run: echo "$KEY" | tr -d '\r' | ssh-add -

      - name: Set envar
        run: export GOPRIVATE=github.com/DrownSelf

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Install golangci
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

      - name: Run linter
        run: golangci-lint run
        
      - name: Run tests
        run: go test -race -vet=off ./...