// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DriverRideResponse driver ride response
//
// swagger:model DriverRideResponse
type DriverRideResponse struct {

	// from
	From string `json:"From,omitempty"`

	// order Id
	OrderID string `json:"OrderId,omitempty"`

	// to
	To string `json:"To,omitempty"`

	// user name
	UserName string `json:"UserName,omitempty"`

	// user phone number
	UserPhoneNumber string `json:"UserPhoneNumber,omitempty"`
}

// Validate validates this driver ride response
func (m *DriverRideResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this driver ride response based on context it is used
func (m *DriverRideResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DriverRideResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DriverRideResponse) UnmarshalBinary(b []byte) error {
	var res DriverRideResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
