// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EndRideRequest end ride request
//
// swagger:model EndRideRequest
type EndRideRequest struct {

	// Id
	ID string `json:"Id,omitempty"`
}

// Validate validates this end ride request
func (m *EndRideRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this end ride request based on context it is used
func (m *EndRideRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EndRideRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndRideRequest) UnmarshalBinary(b []byte) error {
	var res EndRideRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
