// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetDriverResponse get driver response
//
// swagger:model GetDriverResponse
type GetDriverResponse struct {

	// name
	Name string `json:"name,omitempty"`

	// phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// taxi type
	TaxiType string `json:"taxiType,omitempty"`
}

// Validate validates this get driver response
func (m *GetDriverResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get driver response based on context it is used
func (m *GetDriverResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetDriverResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetDriverResponse) UnmarshalBinary(b []byte) error {
	var res GetDriverResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
