// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogInDriverRequest log in driver request
//
// swagger:model LogInDriverRequest
type LogInDriverRequest struct {

	// password
	Password string `json:"password,omitempty"`

	// phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`
}

// Validate validates this log in driver request
func (m *LogInDriverRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log in driver request based on context it is used
func (m *LogInDriverRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogInDriverRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogInDriverRequest) UnmarshalBinary(b []byte) error {
	var res LogInDriverRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
