// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderRateRequest order rate request
//
// swagger:model OrderRateRequest
type OrderRateRequest struct {

	// phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// rating
	Rating int64 `json:"rating,omitempty"`
}

// Validate validates this order rate request
func (m *OrderRateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order rate request based on context it is used
func (m *OrderRateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderRateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderRateRequest) UnmarshalBinary(b []byte) error {
	var res OrderRateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
