// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RateUserRequest rate user request
//
// swagger:model RateUserRequest
type RateUserRequest struct {

	// id
	ID string `json:"id,omitempty"`

	// rating
	Rating int64 `json:"rating,omitempty"`
}

// Validate validates this rate user request
func (m *RateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rate user request based on context it is used
func (m *RateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RateUserRequest) UnmarshalBinary(b []byte) error {
	var res RateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
